### ISSUE TITLE
Add in fighting guaranteed Winked/Romantic Arrow monsters?

### ISSUE THREAD

**Issue by Tokoeka** [Loathing-Associates-Scripting-Society/freecandydotexe#1]
Once you have gotten past the end of the expected window for wink/arrowed monsters, they are guaranteed. Can be tracked with the counter  `1504:Romantic Monster window end loc=* type=wander:rparen.gif` (i think).  Obvs not required, would be nice to have, can probably add a PR for myself, just adding this as a reminder to do so.

**Comment by spaghetti-squash** [comment]
use `getCounters` not `get()`, but yeah, very good idea
