### ISSUE TITLE
Missing dependencies.txt (aborts if CanAdv.ash is not found)

### ISSUE THREAD

**Issue by Malibu-Stacey** [Loathing-Associates-Scripting-Society/freecandydotexe#12]
I ran it on an account which doesn't have many scripts installed & got a failure when it tries to find canadv.ash for some reason.

Easily fixable from the mafia script manager but equally easily fixable in the repo.

**Comment by spaghetti-squash** [comment]
looks like this issue is actually related to the workflows; there is a dependencies.txt that is simply not actually part of the release build. I'll dig into it
