### ISSUE TITLE
Stops after lit houses on first block if you don't have a single item outfit for dark houses.

### ISSUE THREAD

**Issue by Malibu-Stacey** [Loathing-Associates-Scripting-Society/freecandydotexe#13]
Another thing which is easily fixable if you know what the issue is (as in, have read the README.MD) but I found that on a new account which I hadn't already purchased a single item outfit (e.g. beholed bedsheet) it looted the lit houses in the current block then stopped as if it were done without any error message or warning etc.

Perhaps printing a list of acceptable items with current mall_price of each and telling the user why it's stopping would be a more user friendly experience for less technically savvy users.

**Comment by spaghetti-squash** [comment]
It should try to buy one; was the price too high for your autoSatisfy setting?:
