### ISSUE TITLE
Consider more item-generating and turn-generating items

### ISSUE THREAD

**Issue by sundayLOOKplants** [Loathing-Associates-Scripting-Society/freecandydotexe#31]
It'd be useful of the script considered the mafia thumb ring and the can of mixed everything, in addition to lucky gold ring and cheeng.

**Comment by spaghetti-squash** [comment]
Mafia thumb ring only triggers on turn-taking combats; most of our fights are not that.

Can of Mixed Everything, as well as the Sneegleeb, are gated behind the fact that it's extremely difficult to assign a reasonable value to them. Once someone solves that problem they'll be added.

**Comment by spaghetti-squash** [comment]
#41
