### ISSUE TITLE
Re-prioritise Pantsgiving

### ISSUE THREAD

**Issue by Tokoeka** [Loathing-Associates-Scripting-Society/freecandydotexe#4]
This is not a problem per se, but it definitely seems to be prioritising basically everything above pantsgiving as a gnomefolk. Currently only have the 500-turn expansion left (in 450 turns). This /feels/ wrong to me, but I might be off in my calcs.

My calculations are as follows: Great wolf beastly pants give +10 weight, which equates to +~4.5 adventures across 450 turns compared to whatever weight it was prior to the GWBP. +1 stomach can easily beat that?

dont hav pantogram pants that drop anything in this life, so shoudlnt be considering those as I understand it.

Once Ive closeted all my +weight pants, it wears the stainless steel slacks.

Though this might have something to do with what appears to be a -20.94 modifier to Pantsgiving I've just noticed in the maximiser string

Based on the Maximier String and convo with phredd - potentially bad algorithm for picking the pantsgiving food?

**Comment by spaghetti-squash** [comment]
I believe the issue here is that dreadsylvanian stew is actually a very bad pantsgiving food to use
